dist: xenial

services: 
  - mongodb
  - mysql
addons:
  chrome: stable
  firefox: latest
language: java
jdk:
  - openjdk8
sudo: required
before_cache:
  - rm -rf $HOME/.m2/repository/ISPP/G5/INDVELOPERS
cache:
  directories:
  - "$HOME/.m2"
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - mysql -e 'CREATE DATABASE InDvelopers';
install:
  - pip install codacy-coverage
  - pip install selenium
  - sudo apt-get install chromium-browser
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip 
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver
script: 
  - mvn clean package -DskipTests=true
  - mvn test -Dspring.profiles.active=mysql-travis
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml
branches:
  only:
  - main
  - develop
  - "#13"
notifications:
  email: false
warnings_are_errors: false
