warnings_are_errors: false
language: java
jdk:
- oraclejdk8
sudo: true
dist: trusty
services:
  - mongodb
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
branches:
  only:
  - main
  - develop
  - "#13"
