warnings_are_errors: false
dist: trusty
language: java
sudo: required
services: mongodb  
install: true
script: mvn clean package -DskipTests=true
sudo: required
jdk:
  - oraclejdk8
notifications:
  email: false