cloud:
  aws:
    credentials:
      access-key: AKIAR2TANKCFWRFOA3WG
      secret-key: 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
    region:
      static: eu-west-3
    stack:
      auto: false

application:
  bucket:
    name: indvelopers


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5GB
      max-file-size: 5GB
      max-request-size: 5GB